// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPMtT5gFaPBCyIZcO-vgEa53Kc3QKkftQ',
    appId: '1:807456920882:web:de404722b92b471f9f732b',
    messagingSenderId: '807456920882',
    projectId: 'team-a3169',
    authDomain: 'team-a3169.firebaseapp.com',
    storageBucket: 'team-a3169.firebasestorage.app',
    measurementId: 'G-WCPX5K9GKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXfySLPTGwDkZu4_o2jaaeRJ3uVDB2QLU',
    appId: '1:807456920882:android:a1d0f3a1a03757929f732b',
    messagingSenderId: '807456920882',
    projectId: 'team-a3169',
    storageBucket: 'team-a3169.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG-QvUWEHg0CBol-y3wGJGNz_W80_jcxA',
    appId: '1:807456920882:ios:baa3fc238b9ca1409f732b',
    messagingSenderId: '807456920882',
    projectId: 'team-a3169',
    storageBucket: 'team-a3169.firebasestorage.app',
    iosBundleId: 'com.example.teamproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG-QvUWEHg0CBol-y3wGJGNz_W80_jcxA',
    appId: '1:807456920882:ios:baa3fc238b9ca1409f732b',
    messagingSenderId: '807456920882',
    projectId: 'team-a3169',
    storageBucket: 'team-a3169.firebasestorage.app',
    iosBundleId: 'com.example.teamproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPMtT5gFaPBCyIZcO-vgEa53Kc3QKkftQ',
    appId: '1:807456920882:web:59b6c68776e67cf39f732b',
    messagingSenderId: '807456920882',
    projectId: 'team-a3169',
    authDomain: 'team-a3169.firebaseapp.com',
    storageBucket: 'team-a3169.firebasestorage.app',
    measurementId: 'G-18W0QBLFZR',
  );

}